%{
//this FIRST 
//this code here in.l will break the input down into tokens
//parser then the.y will take these tokens in turn them into non-tokens/variables to see if its valid

#include "cmd_data.h"
#include "cmd_parse.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* The following definition ensures that helpful syntax errors are printed: do not  */
#define YY_USER_ACTION \
    yylloc->first_line = yylloc->last_line; \
    yylloc->first_column = yylloc->last_column; \
    for(int i = 0; yytext[i] != '\0'; i++) { \
        if(yytext[i] == '\n') { \
            yylloc->last_line++; \
            yylloc->last_column = 0; \
        } \
        else { \
            yylloc->last_column++; \
        } \
    }

/* The definition below allows for interactive input. */
#define YY_USER_INIT \
  yy_set_interactive(yyin == stdin);

%}

%option outfile="cmd_lex.c" header-file="cmd_lex.h"
%option reentrant noyywrap
%option bison-bridge bison-locations


%%

"$"     { return LABEL; }
"%"     { return VARREF; }
"/"     { return OPTSTART; }
"="     { return OPTPAIR; }
"."     { return CMDSEP; }
"("     { return LPAR; }
")"     { return RPAR; }
"{"     { return LBRACE; }
"}"     { return RBRACE; }

[0-9]+ { yylval->int_temp = atoi(yytext); return INT; }

-?[0-9]+\.[0-9]+ { yylval->flt_temp = atof(yytext); return FLT; }

[a-zA-Z][a-zA-Z0-9]+    { yylval->str_temp= strdup(yytext); return SYM; }

\"([^\\\"]|\\.)*\" { yylval->str_temp = strdup(yytext); return STR;}

[ \n\r\f\t]*  { continue; } //this is for white spaces

%%
